target: Survived
uid: PassengerId

ingest_split_parameters:  
  random_state: 43
  train_size: 0.5
  test_size: 0.5

pipeline_parameters:

  set_df_index_kw_args:
    df_index_col: PassengerId

  create_title_cat_kw_args:
    source_column: 'Name'
    dest_column: 'title_cat'
    title_codes:
      Mr: "gen_male"        
      Mrs: "gen_female"       
      Miss: "young_female"      
      Master: "young_male"    
      Don: "other_male"       
      Rev: "other_male" 
      Dr: "other_male"        
      Mme: "gen_female"      
      Ms: "gen_female"      
      Major: "other_male"     
      Lady: "other_female"      
      Sir: "other_male"       
      Mlle: "young_female"     
      Col: "other_male"       
      Capt: "other_female"      
      Countess: "other_female"  
      Jonkheer: "other_male"
      Dona: "other_female"

  drop_columns_kw_args:
    drop_column_names:
      - Cabin
      - Fare
      - Name
